// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvTfpz63KAshTrUTd-8NUxC3IEGhgWvOc',
    appId: '1:353140944413:web:440315ea4af014f45620f4',
    messagingSenderId: '353140944413',
    projectId: 'flutterfire-g211200019-rafly',
    authDomain: 'flutterfire-g211200019-rafly.firebaseapp.com',
    storageBucket: 'flutterfire-g211200019-rafly.appspot.com',
    measurementId: 'G-FZPB9VJS44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC37gaaxFLL4T4xWJAqhgIDHD5ddpQcVdY',
    appId: '1:353140944413:android:96e92d4af7967dfa5620f4',
    messagingSenderId: '353140944413',
    projectId: 'flutterfire-g211200019-rafly',
    storageBucket: 'flutterfire-g211200019-rafly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC5Bos9LFXvAc1x9vpaFRrj4cG8lWBG08',
    appId: '1:353140944413:ios:4ff75ca52046696c5620f4',
    messagingSenderId: '353140944413',
    projectId: 'flutterfire-g211200019-rafly',
    storageBucket: 'flutterfire-g211200019-rafly.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC5Bos9LFXvAc1x9vpaFRrj4cG8lWBG08',
    appId: '1:353140944413:ios:8e260461df1d953f5620f4',
    messagingSenderId: '353140944413',
    projectId: 'flutterfire-g211200019-rafly',
    storageBucket: 'flutterfire-g211200019-rafly.appspot.com',
    iosBundleId: 'com.example.flutterlist.RunnerTests',
  );
}
